In [115]:
import numpy as np
import re

# 1 sleep equation #1

In [2]:
date = '''totwrk                       -0.169***         
                              (0.018)          
                                               
age                           2.689*           
                              (1.469)          
                                               
south                        101.568**         
                             (41.837)          
                                               
male                         87.669**          
                             (35.104)          
                                               
smsa                         -54.748*          
                             (33.123)          
                                               
yngkid                        -13.962          
                             (50.341)          
                                               
marr                          31.211           
                             (42.233)          
                                               
Constant                    3450.913***        
                             (80.726) '''

In [3]:
date_lst = re.findall(r'([-+]?\d+.\d+)' , date)
date_lst

['-0.169',
 '0.018',
 '2.689',
 '1.469',
 '101.568',
 '41.837',
 '87.669',
 '35.104',
 '-54.748',
 '33.123',
 '-13.962',
 '50.341',
 '31.211',
 '42.233',
 '3450.913',
 '80.726']

In [4]:
beta = np.reshape(date_lst , (8,2))
beta

array([['-0.169', '0.018'],
       ['2.689', '1.469'],
       ['101.568', '41.837'],
       ['87.669', '35.104'],
       ['-54.748', '33.123'],
       ['-13.962', '50.341'],
       ['31.211', '42.233'],
       ['3450.913', '80.726']], dtype='<U8')

In [5]:
beta[:,0]

array(['-0.169', '2.689', '101.568', '87.669', '-54.748', '-13.962',
       '31.211', '3450.913'], dtype='<U8')

In [6]:
beta = beta[:,0].astype(float)
beta

array([-1.690000e-01,  2.689000e+00,  1.015680e+02,  8.766900e+01,
       -5.474800e+01, -1.396200e+01,  3.121100e+01,  3.450913e+03])

In [7]:
empiric = '''  totwrk age south male smsa yngkid marr
1  2150  37    0    1    1     0     1  
2  1950  28    1    1    0     1     0  
3  2240  26    0    0    1     0     0  '''

In [8]:
X = re.findall (r'([-+]?\d+)' , empiric)
X

['1',
 '2150',
 '37',
 '0',
 '1',
 '1',
 '0',
 '1',
 '2',
 '1950',
 '28',
 '1',
 '1',
 '0',
 '1',
 '0',
 '3',
 '2240',
 '26',
 '0',
 '0',
 '1',
 '0',
 '0']

In [9]:
X = np.reshape(X , (3,8))
X

array([['1', '2150', '37', '0', '1', '1', '0', '1'],
       ['2', '1950', '28', '1', '1', '0', '1', '0'],
       ['3', '2240', '26', '0', '0', '1', '0', '0']], dtype='<U4')

In [10]:
X = np.delete (X, 0, 1)
X

array([['2150', '37', '0', '1', '1', '0', '1'],
       ['1950', '28', '1', '1', '0', '1', '0'],
       ['2240', '26', '0', '0', '1', '0', '0']], dtype='<U4')

In [11]:
X = np.c_[X,np.ones(3)]
X

array([['2150', '37', '0', '1', '1', '0', '1', '1.0'],
       ['1950', '28', '1', '1', '0', '1', '0', '1.0'],
       ['2240', '26', '0', '0', '1', '0', '0', '1.0']], dtype='<U32')

In [12]:
beta = beta.astype(float)
X = X.astype(float)

In [13]:
X@beta

array([3251.188, 3371.93 , 3087.519])

# 2 sleep equation #2

In [14]:
date1 = '''totwrk                       -0.167***         
                              (0.018)          
                                               
age                           -6.255           
                             (11.191)          
                                               
I(age2)                        0.109           
                              (0.134)          
                                               
south                       114.547***         
                             (40.637)          
                                               
male                         90.457***         
                             (34.257)          
                                               
Constant                    3613.995***        
                             (218.433)'''

In [15]:
date_lst1 = re.findall(r'([-+]?\d+.\d+)' , date1)
date_lst1

['-0.167',
 '0.018',
 '-6.255',
 '11.191',
 '0.109',
 '0.134',
 '114.547',
 '40.637',
 '90.457',
 '34.257',
 '3613.995',
 '218.433']

In [16]:
beta1 = np.reshape(date_lst1 , (6,2))
beta1

array([['-0.167', '0.018'],
       ['-6.255', '11.191'],
       ['0.109', '0.134'],
       ['114.547', '40.637'],
       ['90.457', '34.257'],
       ['3613.995', '218.433']], dtype='<U8')

In [17]:
beta1[:,0]

array(['-0.167', '-6.255', '0.109', '114.547', '90.457', '3613.995'],
      dtype='<U8')

In [18]:
beta1 = beta1[:,0].astype(float)
beta1

array([-1.670000e-01, -6.255000e+00,  1.090000e-01,  1.145470e+02,
        9.045700e+01,  3.613995e+03])

In [19]:
empiric1 = '''  totwrk age south male
1  2160  32    1    0  
2  1720  24    0    1  
3  2390  44    0    1 '''

In [20]:
X1 = re.findall (r'([-+]?\d+)' , empiric1)
X1

['1',
 '2160',
 '32',
 '1',
 '0',
 '2',
 '1720',
 '24',
 '0',
 '1',
 '3',
 '2390',
 '44',
 '0',
 '1']

In [21]:
X1 = np.reshape(X1 , (3,5))
X1

array([['1', '2160', '32', '1', '0'],
       ['2', '1720', '24', '0', '1'],
       ['3', '2390', '44', '0', '1']], dtype='<U4')

In [22]:
X1 = np.delete (X1, 0, 1)
X1

array([['2160', '32', '1', '0'],
       ['1720', '24', '0', '1'],
       ['2390', '44', '0', '1']], dtype='<U4')

In [23]:
X1 = np.c_[X1,np.ones(3)]
X1

array([['2160', '32', '1', '0', '1.0'],
       ['1720', '24', '0', '1', '1.0'],
       ['2390', '44', '0', '1', '1.0']], dtype='<U32')

In [24]:
X1 = X1.astype(float)

In [25]:
X1_2 = np.insert(X1, 2, (X1[:,1])**2 ,axis=1)
print(X1_2.astype(int))

[[2160   32 1024    1    0    1]
 [1720   24  576    0    1    1]
 [2390   44 1936    0    1    1]]


In [26]:
beta1 = beta1.astype(float)
X1_2 = X1_2.astype(float)

In [27]:
X1_2@beta1

array([3279.278, 3329.876, 3241.126])

# 3 wage equation #1

In [28]:
date2 = '''age                          0.021***          
                              (0.004)          
                                               
IQ                           0.008***          
                              (0.001)          
                                               
south                        -0.099***         
                              (0.027)          
                                               
married                      0.201***          
                              (0.040)          
                                               
urban                        0.175***          
                              (0.028)          
                                               
Constant                     4.974***          
                              (0.165)'''

In [29]:
date_lst2 = re.findall(r'([-+]?\d+.\d+)' , date2)
date_lst2

['0.021',
 '0.004',
 '0.008',
 '0.001',
 '-0.099',
 '0.027',
 '0.201',
 '0.040',
 '0.175',
 '0.028',
 '4.974',
 '0.165']

In [30]:
beta2 = np.reshape(date_lst2 , (6,2))
beta2

array([['0.021', '0.004'],
       ['0.008', '0.001'],
       ['-0.099', '0.027'],
       ['0.201', '0.040'],
       ['0.175', '0.028'],
       ['4.974', '0.165']], dtype='<U6')

In [31]:
beta2[:,0]

array(['0.021', '0.008', '-0.099', '0.201', '0.175', '4.974'], dtype='<U6')

In [32]:
beta2 = beta2[:,0].astype(float)
beta2

array([ 0.021,  0.008, -0.099,  0.201,  0.175,  4.974])

In [33]:
empiric2 = '''  age IQ  south married urban
1 36  105   1      1      1  
2 29  123   0      1      0  
3 25  112   1      0      1  '''

In [34]:
X2 = re.findall (r'([-+]?\d+)' , empiric2)
X2

['1',
 '36',
 '105',
 '1',
 '1',
 '1',
 '2',
 '29',
 '123',
 '0',
 '1',
 '0',
 '3',
 '25',
 '112',
 '1',
 '0',
 '1']

In [35]:
X2 = np.reshape(X2 , (3,6))
X2

array([['1', '36', '105', '1', '1', '1'],
       ['2', '29', '123', '0', '1', '0'],
       ['3', '25', '112', '1', '0', '1']], dtype='<U3')

In [36]:
X2 = np.delete (X2, 0, 1)
X2

array([['36', '105', '1', '1', '1'],
       ['29', '123', '0', '1', '0'],
       ['25', '112', '1', '0', '1']], dtype='<U3')

In [37]:
X2 = np.c_[X2,np.ones(3)]
X2

array([['36', '105', '1', '1', '1', '1.0'],
       ['29', '123', '0', '1', '0', '1.0'],
       ['25', '112', '1', '0', '1', '1.0']], dtype='<U32')

In [38]:
beta2 = beta2.astype(float)
X2 = X2.astype(float)

In [39]:
X2@beta2

array([6.847, 6.768, 6.471])

In [40]:
np.exp(X2@beta2).round(2)

array([941.05, 869.57, 646.13])

# 4 wage equation #2

In [41]:
date3 = '''exper                        0.037***          
                              (0.006)          
                                               
I(exper2)                    -0.001***         
                             (0.0001)          
                                               
female                       -0.363***         
                              (0.040)          
                                               
married                      0.144***          
                              (0.045)          
                                               
smsa                         0.273***          
                              (0.044)          
                                               
Constant                     1.250***          
                              (0.061)'''

In [42]:
date_lst3 = re.findall(r'([-+]?\d+.\d+)' , date3)
date_lst3

['0.037',
 '0.006',
 '-0.001',
 '0.0001',
 '-0.363',
 '0.040',
 '0.144',
 '0.045',
 '0.273',
 '0.044',
 '1.250',
 '0.061']

In [43]:
beta3 = np.reshape(date_lst3 , (6,2))
beta3

array([['0.037', '0.006'],
       ['-0.001', '0.0001'],
       ['-0.363', '0.040'],
       ['0.144', '0.045'],
       ['0.273', '0.044'],
       ['1.250', '0.061']], dtype='<U6')

In [44]:
beta3[:,0]

array(['0.037', '-0.001', '-0.363', '0.144', '0.273', '1.250'],
      dtype='<U6')

In [45]:
beta3 = beta3[:,0].astype(float)
beta3

array([ 3.70e-02, -1.00e-03, -3.63e-01,  1.44e-01,  2.73e-01,  1.25e+00])

In [46]:
empiric3 = '''  exper female married smsa
1   5     1       1     1  
2  26     0       0     1  
3  38     1       1     0  '''

In [47]:
X3 = re.findall (r'([-+]?\d+)' , empiric3)
X3

['1', '5', '1', '1', '1', '2', '26', '0', '0', '1', '3', '38', '1', '1', '0']

In [48]:
X3 = np.reshape(X3 , (3,5))
X3

array([['1', '5', '1', '1', '1'],
       ['2', '26', '0', '0', '1'],
       ['3', '38', '1', '1', '0']], dtype='<U2')

In [49]:
X3 = np.delete (X3, 0, 1)
X3

array([['5', '1', '1', '1'],
       ['26', '0', '0', '1'],
       ['38', '1', '1', '0']], dtype='<U2')

In [50]:
X3 = np.c_[X3,np.ones(3)]
X3

array([['5', '1', '1', '1', '1.0'],
       ['26', '0', '0', '1', '1.0'],
       ['38', '1', '1', '0', '1.0']], dtype='<U32')

In [51]:
X3 = X3.astype(float)

In [52]:
X3_2 = np.insert(X3, 1, (X3[:,0])**2 ,axis=1)
print(X3_2.astype(int))

[[   5   25    1    1    1    1]
 [  26  676    0    0    1    1]
 [  38 1444    1    1    0    1]]


In [53]:
beta3 = beta3.astype(float)
X3_2 = X3_2.astype(float)

In [54]:
X3_2@beta3

array([1.464, 1.809, 0.993])

In [82]:
np.exp(X3_2@beta3).round(2)

array([4.32, 6.1 , 2.7 ])

# 5 output equation #1

In [55]:
date4 = '''log(capital)                 0.208***          
                              (0.017)          
                                               
log(labour)                  0.715***          
                              (0.023)          
                                               
Constant                     -1.711***         
                              (0.097)'''

In [56]:
date_lst4 = re.findall(r'([-+]?\d+.\d+)' , date4)
date_lst4

['0.208', '0.017', '0.715', '0.023', '-1.711', '0.097']

In [57]:
beta4 = np.reshape(date_lst4 , (3,2))
beta4

array([['0.208', '0.017'],
       ['0.715', '0.023'],
       ['-1.711', '0.097']], dtype='<U6')

In [58]:
beta4[:,0]

array(['0.208', '0.715', '-1.711'], dtype='<U6')

In [59]:
beta4 = beta4[:,0].astype(float)
beta4

array([ 0.208,  0.715, -1.711])

In [60]:
empiric4 = '''  capital labour
1  2.970    85  
2   10.450    60  
3  3.850   105 '''

In [61]:
X4 = re.findall (r'([-+]?\d+.\d+|[-+]?\d+)', empiric4)
X4

['1', '2.970', '85', '2', '10.450', '60', '3', '3.850', '105']

In [62]:
X4 = np.reshape(X4 , (3,3))
X4

array([['1', '2.970', '85'],
       ['2', '10.450', '60'],
       ['3', '3.850', '105']], dtype='<U6')

In [63]:
X4 = np.delete (X4, 0, 1)
X4

array([['2.970', '85'],
       ['10.450', '60'],
       ['3.850', '105']], dtype='<U6')

In [64]:
X4 = np.c_[X4,np.ones(3)]
X4

array([['2.970', '85', '1.0'],
       ['10.450', '60', '1.0'],
       ['3.850', '105', '1.0']], dtype='<U32')

In [65]:
beta4 = beta4.astype(float)
X4 = X4.astype(float)

In [66]:
X4@beta4

array([59.68176, 43.3626 , 74.1648 ])

In [85]:
np.exp(X4@beta4).round(2)

array([8.30728362e+25, 6.79419334e+18, 1.61943452e+32])

# 6 output equation #2

In [91]:
date5 = '''log(capital)                 0.183***          
                              (0.017)          
                                               
log(labour)                  0.515***          
                              (0.083)          
                                               
I(log(capital)2)             0.023***          
                              (0.005)          
                                               
I(log(labour)2)               0.020**          
                              (0.010)          
                                               
Constant                     -1.304***         
                              (0.189)'''

In [92]:
date_lst5 = re.findall(r'([-+]?\d+.\d+)' , date5)
date_lst5

['0.183',
 '0.017',
 '0.515',
 '0.083',
 '0.023',
 '0.005',
 '0.020',
 '0.010',
 '-1.304',
 '0.189']

In [93]:
beta5 = np.reshape(date_lst5 , (5,2))
beta5

array([['0.183', '0.017'],
       ['0.515', '0.083'],
       ['0.023', '0.005'],
       ['0.020', '0.010'],
       ['-1.304', '0.189']], dtype='<U6')

In [94]:
beta5[:,0]

array(['0.183', '0.515', '0.023', '0.020', '-1.304'], dtype='<U6')

In [95]:
beta5 = beta5[:,0].astype(float)
beta5

array([ 0.183,  0.515,  0.023,  0.02 , -1.304])

In [96]:
empiric5 = '''  capital labour
1   22.140   407  
2  7.320   197  
3  0.670    31 '''

In [97]:
X5 = re.findall (r'([-+]?\d+.\d+|[-+]?\d+)', empiric5)
X5

['1', '22.140', '407', '2', '7.320', '197', '3', '0.670', '31']

In [98]:
X5 = np.reshape(X5 , (3,3))
X5

array([['1', '22.140', '407'],
       ['2', '7.320', '197'],
       ['3', '0.670', '31']], dtype='<U6')

In [99]:
X5 = np.delete (X5, 0, 1)
X5

array([['22.140', '407'],
       ['7.320', '197'],
       ['0.670', '31']], dtype='<U6')

In [100]:
X5 = np.c_[X5,np.ones(3)]
X5

array([['22.140', '407', '1.0'],
       ['7.320', '197', '1.0'],
       ['0.670', '31', '1.0']], dtype='<U32')

In [102]:
X5 = X5.astype(float)

In [103]:
X5_2 = np.insert(X5, 2, (X5[:,0])**2 ,axis=1)
print(X5_2.astype(int))

[[ 22 407 490   1]
 [  7 197  53   1]
 [  0  31   0   1]]


In [104]:
X5_3 = np.insert(X5_2, 3, (X5_2[:,1])**2 ,axis=1)
print(X5_3.astype(int))

[[    22    407    490 165649      1]
 [     7    197     53  38809      1]
 [     0     31      0    961      1]]


In [105]:
beta5 = beta5.astype(float)
X5_3 = X5_3.astype(float)

In [106]:
X5_3@beta5

array([3536.6067508,  878.9029552,   34.0139347])

In [114]:
np.exp(X5_3@beta5).round(2)

array([           inf,            inf, 5.91649018e+14])